import { PlanEnum } from "app/_types/Plan";

export const PLAN_NAMES: Record<string, string> = {
    MINI: "Mini Club",
    LOCAL: "Local Club",
    REGIONAL: "Régional Club",
    LARGE: "Grand Club",
    MAX: "Maxi Club",
    DISTRICT: "District+ / Ville",
};

export const PLANS = [
    {
        key: PlanEnum.MINI,
        nom: PLAN_NAMES.MINI,
        couleur: "from-lime-400 to-lime-600",
        cible: "1 à 30 licenciés",
        monthly: 4.99,
        sousTitre: "Tout SimplyFoot pour bien démarrer",
        points: [
            "Calendrier, compositions, documents",
            "Stats essentielles joueur/équipe",
            "Support de mise en route",
        ],
        bonus: "Le choix malin pour passer à l'action",
        badge: "Découverte",
        ctaLabel: "Commencer le mois gratuit",
    },
    {
        key: PlanEnum.LOCAL,
        nom: PLAN_NAMES.LOCAL,
        couleur: "from-yellow-400 to-yellow-600",
        cible: "31 à 75 licenciés",
        monthly: 9.99,
        sousTitre: "Impliquer tout le club et les familles",
        points: [
            "Toutes les fonctionnalités",
            "Présences & évaluations multi-équipes",
            "1 compte parent par joueur",
        ],
        bonus: "Notre plan le plus choisi",
        badge: "Meilleur choix",
        ctaLabel: "Commencer le mois gratuit",
    },
    {
        key: PlanEnum.REGIONAL,
        nom: PLAN_NAMES.REGIONAL,
        couleur: "from-emerald-400 to-emerald-600",
        cible: "76 à 150 licenciés",
        monthly: 14.99,
        sousTitre: "La performance au cœur du projet",
        points: [
            "Reporting avancé (assiduité, blessures)",
            "Espace président / staff dédié",
            "Synchronisation FFF (option)",
        ],
        bonus: "Grandir comme les pros",
        badge: "Performance",
        ctaLabel: "Commencer le mois gratuit",
    },
    {
        key: PlanEnum.LARGE,
        nom: PLAN_NAMES.LARGE,
        couleur: "from-sky-400 to-sky-600",
        cible: "151 à 300 licenciés",
        monthly: 19.99,
        sousTitre: "Gestion fluide pour effectif XXL",
        points: [
            "Outils de performance illimités",
            "Docs illimités par joueur",
            "Priorité support",
        ],
        bonus: "Plus de limites pour le staff",
        ctaLabel: "Commencer le mois gratuit",
    },
    {
        key: PlanEnum.MAX,
        nom: PLAN_NAMES.MAX,
        couleur: "from-cyan-400 to-cyan-600",
        cible: "301 à 500 licenciés",
        monthly: 29.99,
        sousTitre: "La référence, sans compromis",
        points: [
            "Multi-sites & multi-équipes",
            "Comptes illimités (dirigeants, éducateurs, parents)",
            "Intégrations API (calendrier ligue)",
        ],
        bonus: "Pensé pour les clubs structurés",
        ctaLabel: "Commencer le mois gratuit",
    },
    {
        key: PlanEnum.DISTRICT,
        nom: PLAN_NAMES.DISTRICT,
        couleur: "from-rose-500 to-rose-700",
        cible: "+ de 500 licenciés",
        monthly: null,
        sousTitre: "L’excellence sur-mesure",
        points: [
            "Interface custom, intégrations poussées",
            "Accompagnement premium & SLA",
            "Interlocuteur dédié",
        ],
        bonus: "Pensé pour groupements et collectivités",
        ctaLabel: "Parler à un expert",
    },
];