import type {
  DashboardStats,
  Club,
  User,
  AdminBlogArticle,
  AdminLog,
} from './types';

// ─── Dashboard Stats ──────────────────────────────────────────────────────────

export const dashboardStats: DashboardStats = {
  totalClubs: 487,
  totalLicencies: 24350,
  totalArticles: 18,
  activeSubscriptions: 312,
  revenueMonth: 4280,
  clubsBySport: { foot: 245, rugby: 142, handball: 100 },
  licenciesBySport: { foot: 13200, rugby: 7850, handball: 3300 },
  newClubsThisMonth: 12,
  newLicenciesThisMonth: 840,
  topRegions: [
    { region: "Provence-Alpes-Côte d'Azur", clubs: 98, licencies: 5120 },
    { region: 'Occitanie', clubs: 87, licencies: 4480 },
    { region: 'Île-de-France', clubs: 76, licencies: 3950 },
    { region: 'Nouvelle-Aquitaine', clubs: 68, licencies: 3410 },
    { region: 'Auvergne-Rhône-Alpes', clubs: 61, licencies: 3080 },
  ],
  registrationTrend: [
    { month: '2025-01', clubs: 310, licencies: 18200 },
    { month: '2025-02', clubs: 318, licencies: 18750 },
    { month: '2025-03', clubs: 330, licencies: 19400 },
    { month: '2025-04', clubs: 345, licencies: 19900 },
    { month: '2025-05', clubs: 358, licencies: 20350 },
    { month: '2025-06', clubs: 370, licencies: 20800 },
    { month: '2025-07', clubs: 385, licencies: 21400 },
    { month: '2025-08', clubs: 398, licencies: 21900 },
    { month: '2025-09', clubs: 420, licencies: 22700 },
    { month: '2025-10', clubs: 445, licencies: 23400 },
    { month: '2025-11', clubs: 468, licencies: 24000 },
    { month: '2025-12', clubs: 487, licencies: 24350 },
  ],
};

// ─── Clubs ────────────────────────────────────────────────────────────────────

export const mockClubs: Club[] = [
  // ─── FOOT (10) ──────────────────────────────────────────────────────
  {
    id: 'club-foot-001',
    name: 'FC Gardanne',
    sport: 'foot',
    status: 'active',
    city: 'Gardanne',
    department: 'Bouches-du-Rhône',
    region: "Provence-Alpes-Côte d'Azur",
    totalLicencies: 285,
    totalEquipes: 12,
    president: 'Marc Delgado',
    email: 'contact@fcgardanne.fr',
    phone: '04 42 51 12 34',
    createdAt: '2023-09-15',
    lastActivityAt: '2025-12-10',
    plan: 'regional',
    subscriptionEnd: '2026-09-14',
  },
  {
    id: 'club-foot-002',
    name: 'AS Villeurbanne',
    sport: 'foot',
    status: 'active',
    city: 'Villeurbanne',
    department: 'Rhône',
    region: 'Auvergne-Rhône-Alpes',
    totalLicencies: 210,
    totalEquipes: 9,
    president: 'Laurent Morin',
    email: 'secretariat@asvilleurbanne.fr',
    phone: '04 78 03 45 67',
    createdAt: '2023-11-02',
    lastActivityAt: '2025-12-08',
    plan: 'local',
    subscriptionEnd: '2026-11-01',
  },
  {
    id: 'club-foot-003',
    name: 'Étoile Sportive de Blagnac',
    sport: 'foot',
    status: 'active',
    city: 'Blagnac',
    department: 'Haute-Garonne',
    region: 'Occitanie',
    totalLicencies: 175,
    totalEquipes: 8,
    president: 'Philippe Serre',
    email: 'info@esblagnac.fr',
    createdAt: '2024-01-20',
    lastActivityAt: '2025-12-09',
    plan: 'local',
    subscriptionEnd: '2026-01-19',
  },
  {
    id: 'club-foot-004',
    name: 'FC Martigues',
    sport: 'foot',
    status: 'active',
    city: 'Martigues',
    department: 'Bouches-du-Rhône',
    region: "Provence-Alpes-Côte d'Azur",
    totalLicencies: 195,
    totalEquipes: 10,
    president: 'Karim Benziane',
    email: 'contact@fcmartigues.fr',
    phone: '04 42 80 56 78',
    createdAt: '2024-03-10',
    lastActivityAt: '2025-12-11',
    plan: 'regional',
    subscriptionEnd: '2026-03-09',
  },
  {
    id: 'club-foot-005',
    name: 'US Colomiers',
    sport: 'foot',
    status: 'active',
    city: 'Colomiers',
    department: 'Haute-Garonne',
    region: 'Occitanie',
    totalLicencies: 145,
    totalEquipes: 7,
    president: 'Jean-Pierre Vernet',
    email: 'uscolomiers@gmail.com',
    createdAt: '2024-05-18',
    lastActivityAt: '2025-11-28',
    plan: 'mini',
    subscriptionEnd: '2026-05-17',
  },
  {
    id: 'club-foot-006',
    name: 'AS Mantes-la-Jolie',
    sport: 'foot',
    status: 'blocked',
    city: 'Mantes-la-Jolie',
    department: 'Yvelines',
    region: 'Île-de-France',
    totalLicencies: 88,
    totalEquipes: 4,
    president: 'Rachid Boukhris',
    email: 'asmantes@orange.fr',
    createdAt: '2024-06-01',
    lastActivityAt: '2025-09-15',
    plan: 'mini',
    subscriptionEnd: '2025-06-01',
  },
  {
    id: 'club-foot-007',
    name: 'FC Pessac',
    sport: 'foot',
    status: 'active',
    city: 'Pessac',
    department: 'Gironde',
    region: 'Nouvelle-Aquitaine',
    totalLicencies: 230,
    totalEquipes: 10,
    president: 'Arnaud Lafitte',
    email: 'contact@fcpessac.fr',
    phone: '05 56 36 12 89',
    createdAt: '2023-08-25',
    lastActivityAt: '2025-12-12',
    plan: 'elite',
    subscriptionEnd: '2026-08-24',
  },
  {
    id: 'club-foot-008',
    name: 'Entente Sportive Vitrollaise',
    sport: 'foot',
    status: 'active',
    city: 'Vitrolles',
    department: 'Bouches-du-Rhône',
    region: "Provence-Alpes-Côte d'Azur",
    totalLicencies: 160,
    totalEquipes: 7,
    president: 'Stéphane Roux',
    email: 'esvitrolles@gmail.com',
    createdAt: '2024-09-05',
    lastActivityAt: '2025-12-06',
    plan: 'local',
    subscriptionEnd: '2025-09-04',
  },
  {
    id: 'club-foot-009',
    name: 'Olympique de Valence',
    sport: 'foot',
    status: 'pending',
    city: 'Valence',
    department: 'Drôme',
    region: 'Auvergne-Rhône-Alpes',
    totalLicencies: 52,
    totalEquipes: 3,
    president: 'Nicolas Faure',
    email: 'ovalence@gmail.com',
    createdAt: '2025-11-20',
    lastActivityAt: '2025-11-22',
    plan: 'free_trial',
  },
  {
    id: 'club-foot-010',
    name: 'JS Saint-Nazaire',
    sport: 'foot',
    status: 'active',
    city: 'Saint-Nazaire',
    department: 'Loire-Atlantique',
    region: 'Pays de la Loire',
    totalLicencies: 120,
    totalEquipes: 6,
    president: 'Yann Le Goff',
    email: 'contact@jsstnazaire.fr',
    createdAt: '2024-02-14',
    lastActivityAt: '2025-12-07',
    plan: 'local',
    subscriptionEnd: '2026-02-13',
  },

  // ─── RUGBY (10) ─────────────────────────────────────────────────────
  {
    id: 'club-rugby-001',
    name: 'AS Béziers Hérault',
    sport: 'rugby',
    status: 'active',
    city: 'Béziers',
    department: 'Hérault',
    region: 'Occitanie',
    totalLicencies: 180,
    totalEquipes: 8,
    president: 'Jean-Marc Vidal',
    email: 'contact@asbeziers-rugby.fr',
    phone: '04 67 76 23 45',
    createdAt: '2023-07-10',
    lastActivityAt: '2025-12-11',
    plan: 'regional',
    subscriptionEnd: '2026-07-09',
  },
  {
    id: 'club-rugby-002',
    name: 'RC Gaillacois',
    sport: 'rugby',
    status: 'active',
    city: 'Gaillac',
    department: 'Tarn',
    region: 'Occitanie',
    totalLicencies: 230,
    totalEquipes: 10,
    president: 'Patrick Fabre',
    email: 'secretariat@rcgaillac.fr',
    phone: '05 63 57 89 01',
    createdAt: '2023-06-05',
    lastActivityAt: '2025-12-10',
    plan: 'elite',
    subscriptionEnd: '2026-06-04',
  },
  {
    id: 'club-rugby-003',
    name: 'US Tyrossaise',
    sport: 'rugby',
    status: 'active',
    city: 'Saint-Vincent-de-Tyrosse',
    department: 'Landes',
    region: 'Nouvelle-Aquitaine',
    totalLicencies: 155,
    totalEquipes: 7,
    president: 'Benoît Darricau',
    email: 'ustyrosse@gmail.com',
    createdAt: '2024-04-12',
    lastActivityAt: '2025-12-09',
    plan: 'local',
    subscriptionEnd: '2026-04-11',
  },
  {
    id: 'club-rugby-004',
    name: 'Rugby Club Nîmois',
    sport: 'rugby',
    status: 'active',
    city: 'Nîmes',
    department: 'Gard',
    region: 'Occitanie',
    totalLicencies: 140,
    totalEquipes: 6,
    president: 'Olivier Pagès',
    email: 'contact@rcnimois.fr',
    createdAt: '2024-08-22',
    lastActivityAt: '2025-12-05',
    plan: 'local',
    subscriptionEnd: '2026-08-21',
  },
  {
    id: 'club-rugby-005',
    name: 'Stade Aurillacois',
    sport: 'rugby',
    status: 'active',
    city: 'Aurillac',
    department: 'Cantal',
    region: 'Auvergne-Rhône-Alpes',
    totalLicencies: 195,
    totalEquipes: 9,
    president: 'François Chabrier',
    email: 'admin@stadeaurillacois.fr',
    phone: '04 71 48 67 23',
    createdAt: '2023-10-01',
    lastActivityAt: '2025-12-12',
    plan: 'regional',
    subscriptionEnd: '2026-09-30',
  },
  {
    id: 'club-rugby-006',
    name: 'RC Sauveterre',
    sport: 'rugby',
    status: 'active',
    city: 'Sauveterre-de-Béarn',
    department: 'Pyrénées-Atlantiques',
    region: 'Nouvelle-Aquitaine',
    totalLicencies: 98,
    totalEquipes: 5,
    president: 'Michel Etchegaray',
    email: 'rcsauveterre@orange.fr',
    createdAt: '2024-07-15',
    lastActivityAt: '2025-11-30',
    plan: 'mini',
    subscriptionEnd: '2026-07-14',
  },
  {
    id: 'club-rugby-007',
    name: 'Avenir Rugby Castres',
    sport: 'rugby',
    status: 'blocked',
    city: 'Castres',
    department: 'Tarn',
    region: 'Occitanie',
    totalLicencies: 72,
    totalEquipes: 4,
    president: 'Didier Marty',
    email: 'arc.castres@gmail.com',
    createdAt: '2024-10-08',
    lastActivityAt: '2025-08-20',
    plan: 'mini',
    subscriptionEnd: '2025-10-07',
  },
  {
    id: 'club-rugby-008',
    name: 'RC Massy',
    sport: 'rugby',
    status: 'active',
    city: 'Massy',
    department: 'Essonne',
    region: 'Île-de-France',
    totalLicencies: 165,
    totalEquipes: 7,
    president: 'Antoine Dupré',
    email: 'contact@rcmassy.fr',
    phone: '01 69 53 12 45',
    createdAt: '2024-01-30',
    lastActivityAt: '2025-12-08',
    plan: 'regional',
    subscriptionEnd: '2026-01-29',
  },
  {
    id: 'club-rugby-009',
    name: 'Stade Dijonnais Rugby',
    sport: 'rugby',
    status: 'pending',
    city: 'Dijon',
    department: "Côte-d'Or",
    region: 'Bourgogne-Franche-Comté',
    totalLicencies: 38,
    totalEquipes: 2,
    president: 'Rémi Blanchard',
    email: 'sdr.dijon@gmail.com',
    createdAt: '2025-12-01',
    lastActivityAt: '2025-12-03',
    plan: 'free_trial',
  },
  {
    id: 'club-rugby-010',
    name: 'Rugby Club Agenais Amateurs',
    sport: 'rugby',
    status: 'active',
    city: 'Agen',
    department: 'Lot-et-Garonne',
    region: 'Nouvelle-Aquitaine',
    totalLicencies: 210,
    totalEquipes: 9,
    president: 'Christophe Duval',
    email: 'amateurs@rcagenais.fr',
    createdAt: '2023-09-01',
    lastActivityAt: '2025-12-11',
    plan: 'elite',
    subscriptionEnd: '2026-08-31',
  },

  // ─── HANDBALL (10) ──────────────────────────────────────────────────
  {
    id: 'club-hand-001',
    name: 'Montpellier HB Amateur',
    sport: 'handball',
    status: 'active',
    city: 'Montpellier',
    department: 'Hérault',
    region: 'Occitanie',
    totalLicencies: 250,
    totalEquipes: 12,
    president: 'Nathalie Redon',
    email: 'amateur@mhb.fr',
    phone: '04 67 64 78 90',
    createdAt: '2023-09-10',
    lastActivityAt: '2025-12-12',
    plan: 'elite',
    subscriptionEnd: '2026-09-09',
  },
  {
    id: 'club-hand-002',
    name: 'HBC Schiltigheim',
    sport: 'handball',
    status: 'active',
    city: 'Schiltigheim',
    department: 'Bas-Rhin',
    region: 'Grand Est',
    totalLicencies: 135,
    totalEquipes: 6,
    president: 'Thomas Kieffer',
    email: 'contact@hbcschiltigheim.fr',
    createdAt: '2024-02-20',
    lastActivityAt: '2025-12-09',
    plan: 'local',
    subscriptionEnd: '2026-02-19',
  },
  {
    id: 'club-hand-003',
    name: 'Cabestany Handball',
    sport: 'handball',
    status: 'active',
    city: 'Cabestany',
    department: 'Pyrénées-Orientales',
    region: 'Occitanie',
    totalLicencies: 110,
    totalEquipes: 5,
    president: 'Sylvain Estève',
    email: 'cabestanyhand@gmail.com',
    createdAt: '2024-06-10',
    lastActivityAt: '2025-12-07',
    plan: 'local',
    subscriptionEnd: '2026-06-09',
  },
  {
    id: 'club-hand-004',
    name: 'HB Jacou',
    sport: 'handball',
    status: 'active',
    city: 'Jacou',
    department: 'Hérault',
    region: 'Occitanie',
    totalLicencies: 95,
    totalEquipes: 5,
    president: 'Marie-Claire Bonnet',
    email: 'hbjacou@gmail.com',
    createdAt: '2024-09-01',
    lastActivityAt: '2025-12-10',
    plan: 'mini',
    subscriptionEnd: '2026-08-31',
  },
  {
    id: 'club-hand-005',
    name: 'Sérignan Valras HB',
    sport: 'handball',
    status: 'active',
    city: 'Sérignan',
    department: 'Hérault',
    region: 'Occitanie',
    totalLicencies: 88,
    totalEquipes: 4,
    president: 'Bruno Cros',
    email: 'svhb@orange.fr',
    createdAt: '2024-10-15',
    lastActivityAt: '2025-12-04',
    plan: 'mini',
    subscriptionEnd: '2026-10-14',
  },
  {
    id: 'club-hand-006',
    name: 'Handball Club de Nantes',
    sport: 'handball',
    status: 'active',
    city: 'Nantes',
    department: 'Loire-Atlantique',
    region: 'Pays de la Loire',
    totalLicencies: 300,
    totalEquipes: 14,
    president: 'Éric Gaudin',
    email: 'contact@hbcnantes-amateur.fr',
    phone: '02 40 89 56 12',
    createdAt: '2023-07-20',
    lastActivityAt: '2025-12-11',
    plan: 'custom',
    subscriptionEnd: '2026-07-19',
  },
  {
    id: 'club-hand-007',
    name: 'Frontignan Handball',
    sport: 'handball',
    status: 'active',
    city: 'Frontignan',
    department: 'Hérault',
    region: 'Occitanie',
    totalLicencies: 78,
    totalEquipes: 4,
    president: 'Isabelle Mercier',
    email: 'frontignanhand@gmail.com',
    createdAt: '2025-01-10',
    lastActivityAt: '2025-12-06',
    plan: 'mini',
    subscriptionEnd: '2026-01-09',
  },
  {
    id: 'club-hand-008',
    name: 'Aix Université Club HB',
    sport: 'handball',
    status: 'blocked',
    city: 'Aix-en-Provence',
    department: 'Bouches-du-Rhône',
    region: "Provence-Alpes-Côte d'Azur",
    totalLicencies: 45,
    totalEquipes: 3,
    president: 'Guillaume Rossi',
    email: 'auchandball@gmail.com',
    createdAt: '2024-11-05',
    lastActivityAt: '2025-07-12',
    plan: 'free_trial',
  },
  {
    id: 'club-hand-009',
    name: 'HBC Strasbourg',
    sport: 'handball',
    status: 'active',
    city: 'Strasbourg',
    department: 'Bas-Rhin',
    region: 'Grand Est',
    totalLicencies: 185,
    totalEquipes: 8,
    president: 'Frédéric Muller',
    email: 'contact@hbcstrasbourg.fr',
    phone: '03 88 15 67 34',
    createdAt: '2023-08-18',
    lastActivityAt: '2025-12-12',
    plan: 'regional',
    subscriptionEnd: '2026-08-17',
  },
  {
    id: 'club-hand-010',
    name: 'Pézenas Handball',
    sport: 'handball',
    status: 'pending',
    city: 'Pézenas',
    department: 'Hérault',
    region: 'Occitanie',
    totalLicencies: 20,
    totalEquipes: 2,
    president: 'Valérie Durand',
    email: 'pezenashand@gmail.com',
    createdAt: '2025-11-28',
    lastActivityAt: '2025-12-01',
    plan: 'free_trial',
  },
];

// ─── Users ────────────────────────────────────────────────────────────────────

export const mockUsers: User[] = [
  // ─── FC Gardanne (club-foot-001) ────────────────────────────────────
  {
    id: 'user-001',
    firstName: 'Marc',
    lastName: 'Delgado',
    email: 'marc.delgado@fcgardanne.fr',
    phone: '06 12 34 56 78',
    role: 'president',
    sport: 'foot',
    clubId: 'club-foot-001',
    clubName: 'FC Gardanne',
    status: 'active',
    createdAt: '2023-09-15',
    lastLoginAt: '2025-12-10',
  },
  {
    id: 'user-002',
    firstName: 'Sophie',
    lastName: 'Bertin',
    email: 'sophie.bertin@fcgardanne.fr',
    role: 'coach',
    sport: 'foot',
    clubId: 'club-foot-001',
    clubName: 'FC Gardanne',
    status: 'active',
    createdAt: '2023-10-01',
    lastLoginAt: '2025-12-09',
  },
  {
    id: 'user-003',
    firstName: 'Lucas',
    lastName: 'Fernandez',
    email: 'lucas.fernandez@gmail.com',
    role: 'joueur',
    sport: 'foot',
    clubId: 'club-foot-001',
    clubName: 'FC Gardanne',
    status: 'active',
    createdAt: '2024-09-10',
    lastLoginAt: '2025-12-08',
  },
  {
    id: 'user-004',
    firstName: 'Catherine',
    lastName: 'Lambert',
    email: 'c.lambert@orange.fr',
    role: 'parent',
    sport: 'foot',
    clubId: 'club-foot-001',
    clubName: 'FC Gardanne',
    status: 'active',
    createdAt: '2024-09-12',
    lastLoginAt: '2025-11-25',
  },
  // ─── AS Villeurbanne (club-foot-002) ────────────────────────────────
  {
    id: 'user-005',
    firstName: 'Laurent',
    lastName: 'Morin',
    email: 'l.morin@asvilleurbanne.fr',
    phone: '06 23 45 67 89',
    role: 'president',
    sport: 'foot',
    clubId: 'club-foot-002',
    clubName: 'AS Villeurbanne',
    status: 'active',
    createdAt: '2023-11-02',
    lastLoginAt: '2025-12-08',
  },
  {
    id: 'user-006',
    firstName: 'Émilie',
    lastName: 'Dufour',
    email: 'emilie.dufour@gmail.com',
    role: 'coach',
    sport: 'foot',
    clubId: 'club-foot-002',
    clubName: 'AS Villeurbanne',
    status: 'active',
    createdAt: '2024-01-15',
    lastLoginAt: '2025-12-07',
  },
  // ─── FC Martigues (club-foot-004) ──────────────────────────────────
  {
    id: 'user-007',
    firstName: 'Karim',
    lastName: 'Benziane',
    email: 'k.benziane@fcmartigues.fr',
    phone: '06 34 56 78 90',
    role: 'president',
    sport: 'foot',
    clubId: 'club-foot-004',
    clubName: 'FC Martigues',
    status: 'active',
    createdAt: '2024-03-10',
    lastLoginAt: '2025-12-11',
  },
  {
    id: 'user-008',
    firstName: 'Thierry',
    lastName: 'Gonzalez',
    email: 'thierry.gonzalez@gmail.com',
    role: 'coach',
    sport: 'foot',
    clubId: 'club-foot-004',
    clubName: 'FC Martigues',
    status: 'active',
    createdAt: '2024-03-15',
    lastLoginAt: '2025-12-10',
  },
  {
    id: 'user-009',
    firstName: 'Maxime',
    lastName: 'Picard',
    email: 'maxime.picard@hotmail.fr',
    role: 'joueur',
    sport: 'foot',
    clubId: 'club-foot-004',
    clubName: 'FC Martigues',
    status: 'active',
    createdAt: '2024-09-01',
    lastLoginAt: '2025-12-06',
  },
  // ─── FC Pessac (club-foot-007) ─────────────────────────────────────
  {
    id: 'user-010',
    firstName: 'Arnaud',
    lastName: 'Lafitte',
    email: 'a.lafitte@fcpessac.fr',
    phone: '06 45 67 89 01',
    role: 'president',
    sport: 'foot',
    clubId: 'club-foot-007',
    clubName: 'FC Pessac',
    status: 'active',
    createdAt: '2023-08-25',
    lastLoginAt: '2025-12-12',
  },
  {
    id: 'user-011',
    firstName: 'Sandrine',
    lastName: 'Dupuis',
    email: 'sandrine.dupuis@gmail.com',
    role: 'parent',
    sport: 'foot',
    clubId: 'club-foot-007',
    clubName: 'FC Pessac',
    status: 'active',
    createdAt: '2024-09-05',
    lastLoginAt: '2025-11-18',
  },
  // ─── AS Mantes-la-Jolie (club-foot-006) ────────────────────────────
  {
    id: 'user-012',
    firstName: 'Rachid',
    lastName: 'Boukhris',
    email: 'r.boukhris@asmantes.fr',
    role: 'president',
    sport: 'foot',
    clubId: 'club-foot-006',
    clubName: 'AS Mantes-la-Jolie',
    status: 'blocked',
    createdAt: '2024-06-01',
    lastLoginAt: '2025-09-15',
  },
  // ─── JS Saint-Nazaire (club-foot-010) ──────────────────────────────
  {
    id: 'user-013',
    firstName: 'Yann',
    lastName: 'Le Goff',
    email: 'yann.legoff@jsstnazaire.fr',
    role: 'president',
    sport: 'foot',
    clubId: 'club-foot-010',
    clubName: 'JS Saint-Nazaire',
    status: 'active',
    createdAt: '2024-02-14',
    lastLoginAt: '2025-12-07',
  },
  {
    id: 'user-014',
    firstName: 'Nolwenn',
    lastName: 'Kergoat',
    email: 'nolwenn.k@gmail.com',
    role: 'coach',
    sport: 'foot',
    clubId: 'club-foot-010',
    clubName: 'JS Saint-Nazaire',
    status: 'active',
    createdAt: '2024-03-01',
    lastLoginAt: '2025-12-05',
  },
  // ─── Olympique de Valence (club-foot-009) ──────────────────────────
  {
    id: 'user-015',
    firstName: 'Nicolas',
    lastName: 'Faure',
    email: 'nicolas.faure@ovalence.fr',
    role: 'president',
    sport: 'foot',
    clubId: 'club-foot-009',
    clubName: 'Olympique de Valence',
    status: 'pending',
    createdAt: '2025-11-20',
    lastLoginAt: '2025-11-22',
  },
  // ─── ES Blagnac (club-foot-003) ────────────────────────────────────
  {
    id: 'user-016',
    firstName: 'Philippe',
    lastName: 'Serre',
    email: 'p.serre@esblagnac.fr',
    role: 'president',
    sport: 'foot',
    clubId: 'club-foot-003',
    clubName: 'Étoile Sportive de Blagnac',
    status: 'active',
    createdAt: '2024-01-20',
    lastLoginAt: '2025-12-09',
  },
  {
    id: 'user-017',
    firstName: 'Julien',
    lastName: 'Roche',
    email: 'julien.roche@gmail.com',
    role: 'joueur',
    sport: 'foot',
    clubId: 'club-foot-003',
    clubName: 'Étoile Sportive de Blagnac',
    status: 'active',
    createdAt: '2024-09-08',
    lastLoginAt: '2025-12-04',
  },
  // ─── US Colomiers (club-foot-005) ──────────────────────────────────
  {
    id: 'user-018',
    firstName: 'Jean-Pierre',
    lastName: 'Vernet',
    email: 'jp.vernet@uscolomiers.fr',
    role: 'president',
    sport: 'foot',
    clubId: 'club-foot-005',
    clubName: 'US Colomiers',
    status: 'active',
    createdAt: '2024-05-18',
    lastLoginAt: '2025-11-28',
  },
  // ─── ES Vitrollaise (club-foot-008) ────────────────────────────────
  {
    id: 'user-019',
    firstName: 'Stéphane',
    lastName: 'Roux',
    email: 's.roux@esvitrolles.fr',
    role: 'president',
    sport: 'foot',
    clubId: 'club-foot-008',
    clubName: 'Entente Sportive Vitrollaise',
    status: 'active',
    createdAt: '2024-09-05',
    lastLoginAt: '2025-12-06',
  },

  // ─── AS Béziers Hérault (club-rugby-001) ───────────────────────────
  {
    id: 'user-020',
    firstName: 'Jean-Marc',
    lastName: 'Vidal',
    email: 'jm.vidal@asbeziers-rugby.fr',
    phone: '06 56 78 90 12',
    role: 'president',
    sport: 'rugby',
    clubId: 'club-rugby-001',
    clubName: 'AS Béziers Hérault',
    status: 'active',
    createdAt: '2023-07-10',
    lastLoginAt: '2025-12-11',
  },
  {
    id: 'user-021',
    firstName: 'Christophe',
    lastName: 'Azéma',
    email: 'c.azema@gmail.com',
    role: 'coach',
    sport: 'rugby',
    clubId: 'club-rugby-001',
    clubName: 'AS Béziers Hérault',
    status: 'active',
    createdAt: '2023-08-01',
    lastLoginAt: '2025-12-10',
  },
  {
    id: 'user-022',
    firstName: 'Romain',
    lastName: 'Pradel',
    email: 'romain.pradel@hotmail.fr',
    role: 'joueur',
    sport: 'rugby',
    clubId: 'club-rugby-001',
    clubName: 'AS Béziers Hérault',
    status: 'active',
    createdAt: '2024-09-15',
    lastLoginAt: '2025-12-08',
  },
  // ─── RC Gaillacois (club-rugby-002) ────────────────────────────────
  {
    id: 'user-023',
    firstName: 'Patrick',
    lastName: 'Fabre',
    email: 'p.fabre@rcgaillac.fr',
    phone: '06 67 89 01 23',
    role: 'president',
    sport: 'rugby',
    clubId: 'club-rugby-002',
    clubName: 'RC Gaillacois',
    status: 'active',
    createdAt: '2023-06-05',
    lastLoginAt: '2025-12-10',
  },
  {
    id: 'user-024',
    firstName: 'Mathieu',
    lastName: 'Larroque',
    email: 'mathieu.larroque@gmail.com',
    role: 'coach',
    sport: 'rugby',
    clubId: 'club-rugby-002',
    clubName: 'RC Gaillacois',
    status: 'active',
    createdAt: '2023-07-01',
    lastLoginAt: '2025-12-09',
  },
  {
    id: 'user-025',
    firstName: 'Damien',
    lastName: 'Alfaia',
    email: 'damien.alfaia@gmail.com',
    role: 'joueur',
    sport: 'rugby',
    clubId: 'club-rugby-002',
    clubName: 'RC Gaillacois',
    status: 'active',
    createdAt: '2024-09-20',
    lastLoginAt: '2025-12-05',
  },
  {
    id: 'user-026',
    firstName: 'Véronique',
    lastName: 'Pech',
    email: 'veronique.pech@gmail.com',
    role: 'parent',
    sport: 'rugby',
    clubId: 'club-rugby-002',
    clubName: 'RC Gaillacois',
    status: 'active',
    createdAt: '2024-09-20',
    lastLoginAt: '2025-11-15',
  },
  // ─── US Tyrossaise (club-rugby-003) ────────────────────────────────
  {
    id: 'user-027',
    firstName: 'Benoît',
    lastName: 'Darricau',
    email: 'b.darricau@ustyrosse.fr',
    role: 'president',
    sport: 'rugby',
    clubId: 'club-rugby-003',
    clubName: 'US Tyrossaise',
    status: 'active',
    createdAt: '2024-04-12',
    lastLoginAt: '2025-12-09',
  },
  {
    id: 'user-028',
    firstName: 'Sébastien',
    lastName: 'Lahourcade',
    email: 'seb.lahourcade@orange.fr',
    role: 'coach',
    sport: 'rugby',
    clubId: 'club-rugby-003',
    clubName: 'US Tyrossaise',
    status: 'active',
    createdAt: '2024-05-01',
    lastLoginAt: '2025-12-07',
  },
  // ─── RC Massy (club-rugby-008) ─────────────────────────────────────
  {
    id: 'user-029',
    firstName: 'Antoine',
    lastName: 'Dupré',
    email: 'a.dupre@rcmassy.fr',
    role: 'president',
    sport: 'rugby',
    clubId: 'club-rugby-008',
    clubName: 'RC Massy',
    status: 'active',
    createdAt: '2024-01-30',
    lastLoginAt: '2025-12-08',
  },
  {
    id: 'user-030',
    firstName: 'Adrien',
    lastName: 'Moreau',
    email: 'adrien.moreau@gmail.com',
    role: 'joueur',
    sport: 'rugby',
    clubId: 'club-rugby-008',
    clubName: 'RC Massy',
    status: 'active',
    createdAt: '2024-09-10',
    lastLoginAt: '2025-12-06',
  },
  // ─── RC Nîmois (club-rugby-004) ────────────────────────────────────
  {
    id: 'user-031',
    firstName: 'Olivier',
    lastName: 'Pagès',
    email: 'o.pages@rcnimois.fr',
    role: 'president',
    sport: 'rugby',
    clubId: 'club-rugby-004',
    clubName: 'Rugby Club Nîmois',
    status: 'active',
    createdAt: '2024-08-22',
    lastLoginAt: '2025-12-05',
  },
  // ─── Stade Aurillacois (club-rugby-005) ────────────────────────────
  {
    id: 'user-032',
    firstName: 'François',
    lastName: 'Chabrier',
    email: 'f.chabrier@stadeaurillacois.fr',
    role: 'president',
    sport: 'rugby',
    clubId: 'club-rugby-005',
    clubName: 'Stade Aurillacois',
    status: 'active',
    createdAt: '2023-10-01',
    lastLoginAt: '2025-12-12',
  },
  // ─── RC Sauveterre (club-rugby-006) ────────────────────────────────
  {
    id: 'user-033',
    firstName: 'Michel',
    lastName: 'Etchegaray',
    email: 'm.etchegaray@rcsauveterre.fr',
    role: 'president',
    sport: 'rugby',
    clubId: 'club-rugby-006',
    clubName: 'RC Sauveterre',
    status: 'active',
    createdAt: '2024-07-15',
    lastLoginAt: '2025-11-30',
  },
  // ─── Avenir Rugby Castres (club-rugby-007) ─────────────────────────
  {
    id: 'user-034',
    firstName: 'Didier',
    lastName: 'Marty',
    email: 'd.marty@arc-castres.fr',
    role: 'president',
    sport: 'rugby',
    clubId: 'club-rugby-007',
    clubName: 'Avenir Rugby Castres',
    status: 'blocked',
    createdAt: '2024-10-08',
    lastLoginAt: '2025-08-20',
  },
  // ─── Stade Dijonnais (club-rugby-009) ──────────────────────────────
  {
    id: 'user-035',
    firstName: 'Rémi',
    lastName: 'Blanchard',
    email: 'remi.blanchard@sdr-dijon.fr',
    role: 'president',
    sport: 'rugby',
    clubId: 'club-rugby-009',
    clubName: 'Stade Dijonnais Rugby',
    status: 'pending',
    createdAt: '2025-12-01',
    lastLoginAt: '2025-12-03',
  },
  // ─── RC Agenais (club-rugby-010) ───────────────────────────────────
  {
    id: 'user-036',
    firstName: 'Christophe',
    lastName: 'Duval',
    email: 'c.duval@rcagenais.fr',
    role: 'president',
    sport: 'rugby',
    clubId: 'club-rugby-010',
    clubName: 'Rugby Club Agenais Amateurs',
    status: 'active',
    createdAt: '2023-09-01',
    lastLoginAt: '2025-12-11',
  },
  {
    id: 'user-037',
    firstName: 'Pierre',
    lastName: 'Castaing',
    email: 'pierre.castaing@gmail.com',
    role: 'joueur',
    sport: 'rugby',
    clubId: 'club-rugby-010',
    clubName: 'Rugby Club Agenais Amateurs',
    status: 'active',
    createdAt: '2024-09-05',
    lastLoginAt: '2025-12-09',
  },

  // ─── Montpellier HB Amateur (club-hand-001) ────────────────────────
  {
    id: 'user-038',
    firstName: 'Nathalie',
    lastName: 'Redon',
    email: 'n.redon@mhb-amateur.fr',
    phone: '06 78 90 12 34',
    role: 'president',
    sport: 'handball',
    clubId: 'club-hand-001',
    clubName: 'Montpellier HB Amateur',
    status: 'active',
    createdAt: '2023-09-10',
    lastLoginAt: '2025-12-12',
  },
  {
    id: 'user-039',
    firstName: 'Laurent',
    lastName: 'Mercier',
    email: 'l.mercier@mhb-amateur.fr',
    role: 'coach',
    sport: 'handball',
    clubId: 'club-hand-001',
    clubName: 'Montpellier HB Amateur',
    status: 'active',
    createdAt: '2023-10-01',
    lastLoginAt: '2025-12-11',
  },
  {
    id: 'user-040',
    firstName: 'Clément',
    lastName: 'Fournier',
    email: 'clement.fournier@gmail.com',
    role: 'joueur',
    sport: 'handball',
    clubId: 'club-hand-001',
    clubName: 'Montpellier HB Amateur',
    status: 'active',
    createdAt: '2024-09-12',
    lastLoginAt: '2025-12-10',
  },
  {
    id: 'user-041',
    firstName: 'Aurélie',
    lastName: 'Garnier',
    email: 'aurelie.garnier@hotmail.fr',
    role: 'parent',
    sport: 'handball',
    clubId: 'club-hand-001',
    clubName: 'Montpellier HB Amateur',
    status: 'active',
    createdAt: '2024-09-14',
    lastLoginAt: '2025-11-20',
  },
  // ─── HBC Schiltigheim (club-hand-002) ──────────────────────────────
  {
    id: 'user-042',
    firstName: 'Thomas',
    lastName: 'Kieffer',
    email: 't.kieffer@hbcschiltigheim.fr',
    role: 'president',
    sport: 'handball',
    clubId: 'club-hand-002',
    clubName: 'HBC Schiltigheim',
    status: 'active',
    createdAt: '2024-02-20',
    lastLoginAt: '2025-12-09',
  },
  {
    id: 'user-043',
    firstName: 'Élodie',
    lastName: 'Schneider',
    email: 'elodie.schneider@gmail.com',
    role: 'coach',
    sport: 'handball',
    clubId: 'club-hand-002',
    clubName: 'HBC Schiltigheim',
    status: 'active',
    createdAt: '2024-03-10',
    lastLoginAt: '2025-12-08',
  },
  // ─── Cabestany Handball (club-hand-003) ────────────────────────────
  {
    id: 'user-044',
    firstName: 'Sylvain',
    lastName: 'Estève',
    email: 's.esteve@cabestanyhand.fr',
    role: 'president',
    sport: 'handball',
    clubId: 'club-hand-003',
    clubName: 'Cabestany Handball',
    status: 'active',
    createdAt: '2024-06-10',
    lastLoginAt: '2025-12-07',
  },
  {
    id: 'user-045',
    firstName: 'Marina',
    lastName: 'Puig',
    email: 'marina.puig@gmail.com',
    role: 'joueur',
    sport: 'handball',
    clubId: 'club-hand-003',
    clubName: 'Cabestany Handball',
    status: 'active',
    createdAt: '2024-09-01',
    lastLoginAt: '2025-12-03',
  },
  // ─── HB Jacou (club-hand-004) ──────────────────────────────────────
  {
    id: 'user-046',
    firstName: 'Marie-Claire',
    lastName: 'Bonnet',
    email: 'mc.bonnet@hbjacou.fr',
    role: 'president',
    sport: 'handball',
    clubId: 'club-hand-004',
    clubName: 'HB Jacou',
    status: 'active',
    createdAt: '2024-09-01',
    lastLoginAt: '2025-12-10',
  },
  // ─── HBC Nantes (club-hand-006) ────────────────────────────────────
  {
    id: 'user-047',
    firstName: 'Éric',
    lastName: 'Gaudin',
    email: 'e.gaudin@hbcnantes-amateur.fr',
    phone: '06 89 01 23 45',
    role: 'president',
    sport: 'handball',
    clubId: 'club-hand-006',
    clubName: 'Handball Club de Nantes',
    status: 'active',
    createdAt: '2023-07-20',
    lastLoginAt: '2025-12-11',
  },
  {
    id: 'user-048',
    firstName: 'Fabien',
    lastName: 'Rivière',
    email: 'fabien.riviere@gmail.com',
    role: 'coach',
    sport: 'handball',
    clubId: 'club-hand-006',
    clubName: 'Handball Club de Nantes',
    status: 'active',
    createdAt: '2023-08-15',
    lastLoginAt: '2025-12-10',
  },
  {
    id: 'user-049',
    firstName: 'Alexandre',
    lastName: 'Lebreton',
    email: 'alex.lebreton@hotmail.fr',
    role: 'joueur',
    sport: 'handball',
    clubId: 'club-hand-006',
    clubName: 'Handball Club de Nantes',
    status: 'active',
    createdAt: '2024-09-08',
    lastLoginAt: '2025-12-08',
  },
  {
    id: 'user-050',
    firstName: 'Christine',
    lastName: 'Moreau',
    email: 'christine.moreau@orange.fr',
    role: 'parent',
    sport: 'handball',
    clubId: 'club-hand-006',
    clubName: 'Handball Club de Nantes',
    status: 'active',
    createdAt: '2024-09-10',
    lastLoginAt: '2025-11-22',
  },
  // ─── Frontignan Handball (club-hand-007) ───────────────────────────
  {
    id: 'user-051',
    firstName: 'Isabelle',
    lastName: 'Mercier',
    email: 'i.mercier@frontignanhand.fr',
    role: 'president',
    sport: 'handball',
    clubId: 'club-hand-007',
    clubName: 'Frontignan Handball',
    status: 'active',
    createdAt: '2025-01-10',
    lastLoginAt: '2025-12-06',
  },
  // ─── Aix UC HB (club-hand-008) ────────────────────────────────────
  {
    id: 'user-052',
    firstName: 'Guillaume',
    lastName: 'Rossi',
    email: 'g.rossi@auchandball.fr',
    role: 'president',
    sport: 'handball',
    clubId: 'club-hand-008',
    clubName: 'Aix Université Club HB',
    status: 'blocked',
    createdAt: '2024-11-05',
    lastLoginAt: '2025-07-12',
  },
  // ─── HBC Strasbourg (club-hand-009) ────────────────────────────────
  {
    id: 'user-053',
    firstName: 'Frédéric',
    lastName: 'Muller',
    email: 'f.muller@hbcstrasbourg.fr',
    phone: '06 90 12 34 56',
    role: 'president',
    sport: 'handball',
    clubId: 'club-hand-009',
    clubName: 'HBC Strasbourg',
    status: 'active',
    createdAt: '2023-08-18',
    lastLoginAt: '2025-12-12',
  },
  {
    id: 'user-054',
    firstName: 'Manon',
    lastName: 'Weber',
    email: 'manon.weber@gmail.com',
    role: 'coach',
    sport: 'handball',
    clubId: 'club-hand-009',
    clubName: 'HBC Strasbourg',
    status: 'active',
    createdAt: '2023-09-05',
    lastLoginAt: '2025-12-10',
  },
  {
    id: 'user-055',
    firstName: 'Bastien',
    lastName: 'Klein',
    email: 'bastien.klein@hotmail.fr',
    role: 'joueur',
    sport: 'handball',
    clubId: 'club-hand-009',
    clubName: 'HBC Strasbourg',
    status: 'active',
    createdAt: '2024-09-18',
    lastLoginAt: '2025-12-09',
  },
  // ─── Sérignan Valras HB (club-hand-005) ────────────────────────────
  {
    id: 'user-056',
    firstName: 'Bruno',
    lastName: 'Cros',
    email: 'b.cros@svhb.fr',
    role: 'president',
    sport: 'handball',
    clubId: 'club-hand-005',
    clubName: 'Sérignan Valras HB',
    status: 'active',
    createdAt: '2024-10-15',
    lastLoginAt: '2025-12-04',
  },
  // ─── Pézenas Handball (club-hand-010) ──────────────────────────────
  {
    id: 'user-057',
    firstName: 'Valérie',
    lastName: 'Durand',
    email: 'v.durand@pezenashand.fr',
    role: 'president',
    sport: 'handball',
    clubId: 'club-hand-010',
    clubName: 'Pézenas Handball',
    status: 'pending',
    createdAt: '2025-11-28',
    lastLoginAt: '2025-12-01',
  },
  // ─── Additional users across clubs ─────────────────────────────────
  {
    id: 'user-058',
    firstName: 'David',
    lastName: 'Nguyen',
    email: 'david.nguyen@gmail.com',
    role: 'joueur',
    sport: 'foot',
    clubId: 'club-foot-002',
    clubName: 'AS Villeurbanne',
    status: 'active',
    createdAt: '2024-09-03',
    lastLoginAt: '2025-12-06',
  },
  {
    id: 'user-059',
    firstName: 'Camille',
    lastName: 'Bertrand',
    email: 'camille.bertrand@gmail.com',
    role: 'joueur',
    sport: 'handball',
    clubId: 'club-hand-001',
    clubName: 'Montpellier HB Amateur',
    status: 'active',
    createdAt: '2024-10-02',
    lastLoginAt: '2025-12-09',
  },
  {
    id: 'user-060',
    firstName: 'Antoine',
    lastName: 'Martin',
    email: 'antoine.martin@orange.fr',
    role: 'parent',
    sport: 'rugby',
    clubId: 'club-rugby-005',
    clubName: 'Stade Aurillacois',
    status: 'active',
    createdAt: '2024-09-25',
    lastLoginAt: '2025-11-10',
  },
];

// ─── Admin Blog Articles ──────────────────────────────────────────────────────

export const mockAdminArticles: AdminBlogArticle[] = [
  // ─── FOOT (6) ───────────────────────────────────────────────────────
  {
    id: 'foot-001',
    title: 'Nouvelle saison : les 5 changements de règles à connaître pour 2025-2026',
    slug: 'nouvelle-saison-les-5-changements-de-regles-a-connaitre-pour-2025-2026',
    brand: 'foot',
    category: 'reglementation',
    status: 'published',
    boosted: true,
    boostExpiry: '2025-09-30',
    author: 'Rédaction SimplyFoot',
    region: 'Île-de-France',
    department: 'Paris',
    publishedAt: '2025-07-12',
    createdAt: '2025-07-10',
    updatedAt: '2025-07-12',
    views: 1850,
    excerpt: 'La FFF a publié les modifications réglementaires qui entreront en vigueur dès septembre.',
    content: '',
  },
  {
    id: 'foot-002',
    title: 'Comment le FC Gardanne a digitalisé la gestion de ses 12 équipes',
    slug: 'comment-le-fc-gardanne-a-digitalise-la-gestion-de-ses-12-equipes',
    brand: 'foot',
    category: 'temoignages',
    status: 'published',
    boosted: false,
    author: 'Sophie Martineau',
    region: "Provence-Alpes-Côte d'Azur",
    department: 'Bouches-du-Rhône',
    publishedAt: '2025-04-18',
    createdAt: '2025-04-15',
    updatedAt: '2025-04-18',
    views: 1240,
    excerpt: "Le FC Gardanne, club phare des Bouches-du-Rhône avec plus de 300 licenciés, a adopté SimplyFoot il y a un an.",
    content: '',
  },
  {
    id: 'foot-003',
    title: 'Calendrier des tournois jeunes en PACA : dates et inscriptions',
    slug: 'calendrier-des-tournois-jeunes-en-paca-dates-et-inscriptions',
    brand: 'foot',
    category: 'evenements',
    status: 'published',
    boosted: false,
    author: 'Rédaction SimplyFoot',
    region: "Provence-Alpes-Côte d'Azur",
    department: 'Var',
    publishedAt: '2025-03-05',
    createdAt: '2025-03-02',
    updatedAt: '2025-03-05',
    views: 980,
    excerpt: "La saison des tournois jeunes approche en région PACA. Retrouvez les dates clés et les modalités d'inscription.",
    content: '',
  },
  {
    id: 'foot-004',
    title: "Convocations automatisées : le retour d'expérience du club de Martigues",
    slug: 'convocations-automatisees-le-retour-d-experience-du-club-de-martigues',
    brand: 'foot',
    category: 'temoignages',
    status: 'published',
    boosted: true,
    boostExpiry: '2025-08-15',
    author: 'Sophie Martineau',
    region: "Provence-Alpes-Côte d'Azur",
    department: 'Bouches-du-Rhône',
    publishedAt: '2025-05-22',
    createdAt: '2025-05-19',
    updatedAt: '2025-05-22',
    views: 1560,
    excerpt: "Le FC Martigues a réduit de 80 % le temps consacré aux convocations grâce à l'automatisation.",
    content: '',
  },
  {
    id: 'foot-005',
    title: 'District 13 : les derniers résultats et classements mis à jour',
    slug: 'district-13-les-derniers-resultats-et-classements-mis-a-jour',
    brand: 'foot',
    category: 'actualite',
    status: 'published',
    boosted: false,
    author: 'Rédaction SimplyFoot',
    region: "Provence-Alpes-Côte d'Azur",
    department: 'Bouches-du-Rhône',
    publishedAt: '2025-03-17',
    createdAt: '2025-03-17',
    updatedAt: '2025-03-17',
    views: 720,
    excerpt: "Retrouvez l'ensemble des résultats du week-end et les classements actualisés du District des Bouches-du-Rhône.",
    content: '',
  },
  {
    id: 'foot-006',
    title: 'Recruter et fidéliser des bénévoles : 7 stratégies qui fonctionnent',
    slug: 'recruter-et-fideliser-des-benevoles-7-strategies-qui-fonctionnent',
    brand: 'foot',
    category: 'conseils',
    status: 'draft',
    boosted: false,
    author: 'Thomas Leclerc',
    region: 'Bretagne',
    department: 'Ille-et-Vilaine',
    createdAt: '2025-09-05',
    updatedAt: '2025-09-08',
    views: 0,
    excerpt: "Le bénévolat est le moteur du football amateur, mais recruter et garder des bénévoles reste un défi.",
    content: '',
  },

  // ─── RUGBY (6) ──────────────────────────────────────────────────────
  {
    id: 'rugby-001',
    title: 'Saison 2025-2026 : le calendrier fédéral est disponible',
    slug: 'saison-2025-2026-le-calendrier-federal-est-disponible',
    brand: 'rugby',
    category: 'actualite',
    status: 'published',
    boosted: true,
    boostExpiry: '2025-09-15',
    author: 'Rédaction SimplyRugby',
    region: 'Occitanie',
    department: 'Haute-Garonne',
    publishedAt: '2025-06-28',
    createdAt: '2025-06-25',
    updatedAt: '2025-06-28',
    views: 2000,
    excerpt: "La FFR a publié le calendrier officiel de la saison 2025-2026 pour l'ensemble des divisions fédérales.",
    content: '',
  },
  {
    id: 'rugby-002',
    title: "L'AS Béziers Hérault passe à SimplyRugby : témoignage du président",
    slug: 'l-as-beziers-herault-passe-a-simplyRugby-temoignage-du-president',
    brand: 'rugby',
    category: 'temoignages',
    status: 'published',
    boosted: false,
    author: 'Claire Dumont',
    region: 'Occitanie',
    department: 'Hérault',
    publishedAt: '2025-02-14',
    createdAt: '2025-02-10',
    updatedAt: '2025-02-14',
    views: 890,
    excerpt: "Avec 180 licenciés et 8 équipes, l'AS Béziers Hérault avait besoin d'un outil adapté au rugby amateur.",
    content: '',
  },
  {
    id: 'rugby-003',
    title: 'Nouvelle réglementation des mêlées en catégories jeunes',
    slug: 'nouvelle-reglementation-des-melees-en-categories-jeunes',
    brand: 'rugby',
    category: 'reglementation',
    status: 'published',
    boosted: false,
    author: 'Rédaction SimplyRugby',
    region: 'Nouvelle-Aquitaine',
    department: 'Gironde',
    publishedAt: '2025-08-03',
    createdAt: '2025-07-30',
    updatedAt: '2025-08-03',
    views: 1320,
    excerpt: 'La FFR renforce les règles de sécurité autour des mêlées pour les catégories M14 et M16.',
    content: '',
  },
  {
    id: 'rugby-004',
    title: 'Organiser un tournoi de rugby à 7 : guide pratique complet',
    slug: 'organiser-un-tournoi-de-rugby-a-7-guide-pratique-complet',
    brand: 'rugby',
    category: 'conseils',
    status: 'published',
    boosted: false,
    author: 'Thomas Leclerc',
    region: 'Auvergne-Rhône-Alpes',
    department: 'Rhône',
    publishedAt: '2025-04-10',
    createdAt: '2025-04-07',
    updatedAt: '2025-04-10',
    views: 1080,
    excerpt: "Le rugby à 7 connaît un essor fulgurant dans les clubs amateurs. Guide complet pour organiser un tournoi réussi.",
    content: '',
  },
  {
    id: 'rugby-005',
    title: 'Résultats Fédérale 3 Poule 5 : tous les scores du week-end',
    slug: 'resultats-federale-3-poule-5-tous-les-scores-du-week-end',
    brand: 'rugby',
    category: 'actualite',
    status: 'archived',
    boosted: false,
    author: 'Rédaction SimplyRugby',
    region: 'Nouvelle-Aquitaine',
    department: 'Pyrénées-Atlantiques',
    publishedAt: '2025-03-16',
    createdAt: '2025-03-16',
    updatedAt: '2025-05-01',
    views: 540,
    excerpt: "La Poule 5 de Fédérale 3 a livré des confrontations disputées ce week-end. Tous les résultats et classements.",
    content: '',
  },
  {
    id: 'rugby-006',
    title: 'Comment gérer un club de rugby avec 200+ licenciés sans stress',
    slug: 'comment-gerer-un-club-de-rugby-avec-200-plus-licencies-sans-stress',
    brand: 'rugby',
    category: 'conseils',
    status: 'published',
    boosted: false,
    author: 'Claire Dumont',
    region: 'Occitanie',
    department: 'Tarn',
    publishedAt: '2025-10-14',
    createdAt: '2025-10-10',
    updatedAt: '2025-10-14',
    views: 670,
    excerpt: "Gérer un club de plus de 200 licenciés peut vite devenir un casse-tête. Les méthodes du RC Gaillacois.",
    content: '',
  },

  // ─── HANDBALL (6) ───────────────────────────────────────────────────
  {
    id: 'handball-001',
    title: 'Créneaux gymnase : comment négocier efficacement avec votre mairie',
    slug: 'creneaux-gymnase-comment-negocier-efficacement-avec-votre-mairie',
    brand: 'handball',
    category: 'conseils',
    status: 'published',
    boosted: false,
    author: 'Thomas Leclerc',
    region: 'Île-de-France',
    department: 'Seine-Saint-Denis',
    publishedAt: '2025-01-20',
    createdAt: '2025-01-17',
    updatedAt: '2025-01-20',
    views: 1450,
    excerpt: "L'accès aux gymnases est le nerf de la guerre pour les clubs de handball. Stratégies concrètes pour obtenir vos créneaux.",
    content: '',
  },
  {
    id: 'handball-002',
    title: 'Les résultats du championnat régional Occitanie mis à jour',
    slug: 'les-resultats-du-championnat-regional-occitanie-mis-a-jour',
    brand: 'handball',
    category: 'actualite',
    status: 'archived',
    boosted: false,
    author: 'Rédaction SimplyHandball',
    region: 'Occitanie',
    department: 'Hérault',
    publishedAt: '2025-01-27',
    createdAt: '2025-01-27',
    updatedAt: '2025-04-01',
    views: 380,
    excerpt: "La 12e journée du championnat régional Occitanie a livré des résultats palpitants.",
    content: '',
  },
  {
    id: 'handball-003',
    title: 'SimplyHandball lance les statistiques avancées par joueur',
    slug: 'simplyhandball-lance-les-statistiques-avancees-par-joueur',
    brand: 'handball',
    category: 'mises-a-jour',
    status: 'published',
    boosted: true,
    boostExpiry: '2025-06-30',
    author: 'Rédaction SimplyHandball',
    region: "Provence-Alpes-Côte d'Azur",
    department: 'Bouches-du-Rhône',
    publishedAt: '2025-02-25',
    createdAt: '2025-02-22',
    updatedAt: '2025-02-25',
    views: 1680,
    excerpt: "Buts, assists, taux de réussite aux tirs, arrêts : un nouveau module de statistiques individuelles.",
    content: '',
  },
  {
    id: 'handball-004',
    title: 'Coupe de France : le parcours remarquable des clubs amateurs en 2025',
    slug: 'coupe-de-france-le-parcours-remarquable-des-clubs-amateurs-en-2025',
    brand: 'handball',
    category: 'actualite',
    status: 'published',
    boosted: false,
    author: 'Claire Dumont',
    region: 'Grand Est',
    department: 'Bas-Rhin',
    publishedAt: '2025-11-18',
    createdAt: '2025-11-15',
    updatedAt: '2025-11-18',
    views: 520,
    excerpt: "L'édition 2025 de la Coupe de France de handball a réservé de belles surprises avec plusieurs clubs amateurs.",
    content: '',
  },
  {
    id: 'handball-005',
    title: 'Gestion des exclusions temporaires : ce que dit le nouveau règlement',
    slug: 'gestion-des-exclusions-temporaires-ce-que-dit-le-nouveau-reglement',
    brand: 'handball',
    category: 'reglementation',
    status: 'published',
    boosted: false,
    author: 'Rédaction SimplyHandball',
    region: 'Hauts-de-France',
    department: 'Nord',
    publishedAt: '2025-08-22',
    createdAt: '2025-08-19',
    updatedAt: '2025-08-22',
    views: 810,
    excerpt: 'La FFHB a modifié les règles relatives aux exclusions temporaires pour la saison 2025-2026.',
    content: '',
  },
  {
    id: 'handball-006',
    title: 'Montpellier HB amateur digitalise sa gestion avec SimplyHandball',
    slug: 'montpellier-hb-amateur-digitalise-sa-gestion-avec-simplyhandball',
    brand: 'handball',
    category: 'temoignages',
    status: 'draft',
    boosted: false,
    author: 'Sophie Martineau',
    region: 'Occitanie',
    department: 'Hérault',
    createdAt: '2025-12-02',
    updatedAt: '2025-12-05',
    views: 0,
    excerpt: "Le Montpellier HB amateur, section distincte du club professionnel, a adopté SimplyHandball pour gérer ses 250 licenciés.",
    content: '',
  },
];

// ─── Admin Logs ───────────────────────────────────────────────────────────────

export const mockLogs: AdminLog[] = [
  {
    id: 'log-001',
    action: 'club.create',
    target: 'Club',
    targetId: 'club-hand-010',
    adminUser: 'admin@simply.fr',
    timestamp: '2025-12-12T14:32:00',
    details: 'Création du club Pézenas Handball (essai gratuit)',
  },
  {
    id: 'log-002',
    action: 'club.status_change',
    target: 'Club',
    targetId: 'club-hand-008',
    adminUser: 'admin@simply.fr',
    timestamp: '2025-12-12T11:15:00',
    details: 'Statut du club Aix Université Club HB passé de "active" à "blocked" — impayé cotisation',
  },
  {
    id: 'log-003',
    action: 'article.publish',
    target: 'Article',
    targetId: 'handball-004',
    adminUser: 'redaction@simply.fr',
    timestamp: '2025-12-11T16:45:00',
    details: 'Publication de l\'article "Coupe de France : le parcours remarquable des clubs amateurs en 2025"',
  },
  {
    id: 'log-004',
    action: 'user.block',
    target: 'User',
    targetId: 'user-034',
    adminUser: 'admin@simply.fr',
    timestamp: '2025-12-11T10:20:00',
    details: 'Blocage du compte de Didier Marty (Avenir Rugby Castres) — compte inactif depuis 4 mois',
  },
  {
    id: 'log-005',
    action: 'club.plan_upgrade',
    target: 'Club',
    targetId: 'club-rugby-002',
    adminUser: 'commercial@simply.fr',
    timestamp: '2025-12-10T09:30:00',
    details: 'RC Gaillacois : passage du plan Régional au plan Élite',
  },
  {
    id: 'log-006',
    action: 'article.boost',
    target: 'Article',
    targetId: 'foot-001',
    adminUser: 'redaction@simply.fr',
    timestamp: '2025-12-10T08:00:00',
    details: 'Boost activé sur l\'article "Nouvelle saison : les 5 changements de règles" — expiration le 30/09/2025',
  },
  {
    id: 'log-007',
    action: 'club.create',
    target: 'Club',
    targetId: 'club-rugby-009',
    adminUser: 'admin@simply.fr',
    timestamp: '2025-12-09T15:10:00',
    details: 'Création du club Stade Dijonnais Rugby (essai gratuit)',
  },
  {
    id: 'log-008',
    action: 'user.create',
    target: 'User',
    targetId: 'user-035',
    adminUser: 'admin@simply.fr',
    timestamp: '2025-12-09T15:12:00',
    details: 'Création du compte de Rémi Blanchard (président, Stade Dijonnais Rugby)',
  },
  {
    id: 'log-009',
    action: 'article.archive',
    target: 'Article',
    targetId: 'rugby-005',
    adminUser: 'redaction@simply.fr',
    timestamp: '2025-12-08T17:00:00',
    details: 'Archivage de l\'article "Résultats Fédérale 3 Poule 5" — contenu périmé',
  },
  {
    id: 'log-010',
    action: 'club.status_change',
    target: 'Club',
    targetId: 'club-foot-006',
    adminUser: 'admin@simply.fr',
    timestamp: '2025-12-07T11:45:00',
    details: 'Statut du club AS Mantes-la-Jolie passé de "active" à "blocked" — abonnement expiré',
  },
  {
    id: 'log-011',
    action: 'user.password_reset',
    target: 'User',
    targetId: 'user-023',
    adminUser: 'support@simply.fr',
    timestamp: '2025-12-06T09:20:00',
    details: 'Réinitialisation du mot de passe pour Patrick Fabre (RC Gaillacois) à sa demande',
  },
  {
    id: 'log-012',
    action: 'club.plan_upgrade',
    target: 'Club',
    targetId: 'club-hand-009',
    adminUser: 'commercial@simply.fr',
    timestamp: '2025-12-05T14:50:00',
    details: 'HBC Strasbourg : passage du plan Local au plan Régional',
  },
  {
    id: 'log-013',
    action: 'article.edit',
    target: 'Article',
    targetId: 'handball-006',
    adminUser: 'redaction@simply.fr',
    timestamp: '2025-12-05T10:30:00',
    details: 'Mise à jour du brouillon "Montpellier HB amateur digitalise sa gestion"',
  },
  {
    id: 'log-014',
    action: 'club.export',
    target: 'Club',
    targetId: '*',
    adminUser: 'admin@simply.fr',
    timestamp: '2025-12-04T16:00:00',
    details: 'Export CSV de la liste complète des clubs (487 entrées)',
  },
  {
    id: 'log-015',
    action: 'user.role_change',
    target: 'User',
    targetId: 'user-039',
    adminUser: 'admin@simply.fr',
    timestamp: '2025-12-03T13:15:00',
    details: 'Laurent Mercier (Montpellier HB Amateur) : rôle changé de "joueur" à "coach"',
  },
];
